### ISSUE TITLE
Set timestamp if not already present

### ISSUE THREAD

**Issue by alexethomas** [rabbitmq/rabbitmq-message-timestamp#1]
Very handy! And of course being a plugin, users can decide whether or not they want Rabbit to set the timestamps.
However, this applies globally - maybe there are cases where some publishers are supplying timestamps that they don't want replaced? E.g.

* a queue is part of a bridge or routing setup and it's the time the message was enqueued upstream that's significant, not the time it was bridged/routed
* (similar) a queue is part of a pipeline of activities and the timestamp reflects the start of the overall pipeline

Generally, I'm thinking of contexts where Rabbit is connecting a variety of different apps with somewhat varying practices. This plugin provides a huge benefit in ensuring that timestamps (and timestamp monitoring :smiley:) will always be available, but if a timestamp is already there there's no reason for it to interfere.

FWIW I think the reason JMS doesn't work like this is that the timestamp is considered internal and typically used for TTL expiry etc. whereas in Rabbit it has no internal role.

**Comment by michaelklishin** [comment]
@alexethomas so your suggestion would be to only timestamp messages that don't already have a timestamp?

**Comment by alexethomas** [comment]
Right, that's all.
(Something policy-driven did cross my mind but I can't see a convincing case for it)

**Comment by biiiipy** [comment]
If it's configurable then why not, but by default it should keep it's current behaviour (users can't be trusted :wink: )

**Comment by michaelklishin** [comment]
@biiiipy when it comes to time and consistent view of it in distributed systems, servers can't be trusted either. So the question comes down to "what would most developers find more convenient".

@alexethomas' point is that it should not be globally configured. So perhaps this can be done via a message header?

**Comment by alexethomas** [comment]
@michaelklishin could you expand on the message header idea? I appreciate I may be trying to make one field serve two purposes (timestamp for the time the message was enqueued vs. time of the start of an activity beginning further upstream) but the "add timestamp if not already present" approach still allows people to be consistent I think.

**Comment by bdshroyer** [comment]
Resolved by [#6](https://github.com/rabbitmq/rabbitmq-message-timestamp/pull/6).

**Comment by biiiipy** [comment]
Too bad it's not possible to opt-out, it means I'll have to maintain a fork with the original behaviour, because this change removes any guarantees of consistent timestamps.

**Comment by michaelklishin** [comment]
@biiiipy I'm not sure how much consistency the original behaviour guaranteed as time can drift to some extent between nodes in a cluster. In any case, if making your publishers not timestamp messages doesn't work for you, you can develop an alternative or maintain a fork, this plugin is really small.
