### ISSUE TITLE
Missing direct link to the binary

### ISSUE THREAD

**Issue by KokaChernov** [rabbitmq/rabbitmq-message-timestamp#14]
I'm trying to built the source codes in the windows environment and it's not that easy. Could you please provide a link to the module that I can copy to the rabbit folder without needing to setup make and other stuff? Like here for example https://github.com/rabbitmq/rabbitmq-lvc-plugin

**Comment by michaelklishin** [comment]
See [Community Plugins](http://www.rabbitmq.com/community-plugins.html) on rabbitmq.com.
