### ISSUE TITLE
Provide a timestamp in miliseconds as well as seconds

### ISSUE THREAD

**Issue by hradilf** [rabbitmq/rabbitmq-message-timestamp#16]
Hi, I have noticed that miliseconds missing in the timestamp (RabbitMQ 3.6.6, Erlang 18.3, tried both available official versions (https://bintray.com/rabbitmq/community-plugins/rabbitmq_message_timestamp/v3.6.x#files).

In your src you have:
Timestamp = os:system_time(seconds)

Any chance to change it to milliseconds and upload new .ez file to plugins repository?

**Comment by michaelklishin** [comment]
@hradilf see https://github.com/rabbitmq/rabbitmq-event-exchange/issues/8. The AMQP 0-9-1 spec mandates that the timestamp property is a value in seconds (inspired by POSIX `time_t`). The only way to pass a value in ms is using a header *in addition* the the one in seconds.

**Comment by hradilf** [comment]
Hi @michaelklishin thank you for your quick answer. If you added the "enhancement" tag, does it mean that you plan to implement this? If so, please, can you provide an estimate when it will implemented (week, month, year,..). Thanks.

**Comment by michaelklishin** [comment]
@hradilf it means that it's a reasonable and specific feature request. I don't have an ETA. Feel free to contribute it.

**Comment by hradilf** [comment]
OK, thanks for the info. Maybe I will try to do it myself or will try to find a colleague from my team (Energy trading, Deutsche Borse Group) who has some experiences with Erlang.

**Comment by hradilf** [comment]
@michaelklishin Please, which branch can I use once I will create merge request? Do you have a preference for the new property name? E.g. "x-timestamp-ms"?

**Comment by michaelklishin** [comment]
@hradilf if this is backwards-compatible (it should be), it can go into into `3.6.x`, which uses the `stable` branch. Otherwise use `master`.

rabbitmq-event-exchange uses `timestamp_in_ms` for header name. What do you think?

**Comment by hradilf** [comment]
@michaelklishin OK. Thanks

**Comment by hradilf** [comment]
@michaelklishin thank you for your merge. Please, would it be possible to place updated version to your download page? https://bintray.com/rabbitmq/community-plugins/rabbitmq_message_timestamp/

**Comment by michaelklishin** [comment]
@hradilf after RabbitMQ 3.6.11 is out.

**Comment by michaelklishin** [comment]
Here's a version produced off the tip of stable:
[rabbitmq_message_timestamp-3.6.11.milestone.g9cdb1c4.ez.zip](https://github.com/rabbitmq/rabbitmq-message-timestamp/files/1169548/rabbitmq_message_timestamp-3.6.11.milestone.g9cdb1c4.ez.zip)
