### ISSUE TITLE
Lost `head_message_timestamp` after restart

### ISSUE THREAD

**Issue by wildloop** [rabbitmq/rabbitmq-message-timestamp#20]
Once set `head_message_timestamp` (by plugin) is lost after rabbitmq restart. 

Is this the expected behavior?

Erlang 20.1, Rabbitmq 3.7.0, rabbitmq-message-timestamp plugin 3.7.0

**Comment by lukebakken** [comment]
Hello,

Please use the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) to ask questions. The RabbitMQ team does not use GitHub issues for issue analysis.

When you post this question to the mailing list, please include complete steps to reproduce this issue. A code sample that reproduces it would be even better, thanks!

Thanks -
Luke
