### ISSUE TITLE
timestamp_in_ms missing via stomp protocol

### ISSUE THREAD

**Issue by brettmc** [rabbitmq/rabbitmq-message-timestamp#21]
Hi.
I've installed v3.7.0 (latest on the community builds) plugin into rabbitmq 3.7.2. I don't see `timestamp_in_ms` header returned via STOMP, but I *am* able to see it via the management console, if I inspect a message. I'm also able to see it via AMQP (using php-amqplib).
To rule out stomp client implementation issues, here it is via telnet:
```
[root@24596575663a app]# telnet
telnet> open mq 61613
Trying 172.24.0.2...
Connected to mq.
Escape character is '^]'.
CONNECT
accept-version:1.2
host:/
login:guest
passcode:guest

^@
CONNECTED
server:RabbitMQ/3.7.2
session:session-NosUdMkAzMWUNqJ6V4ZAoQ
heart-beat:0,0
version:1.2


SUBSCRIBE
id:0
destination:/queue/foo
ack:client

^@
MESSAGE
subscription:0
destination:/queue/foo
message-id:T_0@@session-NosUdMkAzMWUNqJ6V4ZAoQ@@1
redelivered:false
ack:T_0@@session-NosUdMkAzMWUNqJ6V4ZAoQ@@1
timestamp:1515482597
content-type:text/plain
content-length:11

hello world
```
And here is the same message when viewed via the management console:
![message_with_timestamp_in_ms](https://user-images.githubusercontent.com/4978962/34709388-275dad24-f56b-11e7-846a-5000e964e14b.png)

**Comment by michaelklishin** [comment]
STOMP propagates only a certain number of headers and isn't aware of this one. This belongs to rabbitmq/rabbitmq-stomp.
