### ISSUE TITLE
Closing AMQP connections after activating the plugin

### ISSUE THREAD

**Issue by maess89** [rabbitmq/rabbitmq-message-timestamp#22]
I obtained the binary for RabbitMQ 3.6.14 from the following sources:

https://dl.bintray.com/rabbitmq/community-plugins/rabbitmq_message_timestamp-1.0.0.ez
https://dl.bintray.com/rabbitmq/community-plugins/rabbitmq_message_timestamp-3.6.x-0b333722.ez
https://dl.bintray.com/rabbitmq/community-plugins/rabbitmq_message_timestamp-3.6.x-6a09867d.ez

The reason I tried several versions is that the link on the community plugin list is broken:

http://www.rabbitmq.com/community-plugins.html
   rabbitmq_message_timestamp 
   Download for 3.6.x 
   is referencing https://dl.bintray.com/rabbitmq/community-plugins/rabbitmq_delayed_message_exchange-0.0.1.ez

However, if I enable the plugin using one of the provided binaries my Clients can't connect!

The error log in /var/log/rabbitmq/... is as follows:

> =ERROR REPORT==== 11-Jan-2018::11:51:14 ===
> Error on AMQP connection <0.440.0> (_IP_:55842 -> _IP_:5672, vhost: '/', user: 'admin', state: running), channel 1:
> {{case_clause,
>      {'EXIT',
>          {undef,
>              [{os,system_time,[seconds],[]},
>               {rabbit_timestamp_interceptor,intercept,3,
>                   [{file,"src/rabbit_timestamp_interceptor.erl"},{line,46}]},
>               {rabbit_channel_interceptor,call_module,4,
>                   [{file,"src/rabbit_channel_interceptor.erl"},{line,74}]},
>               {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
>               {rabbit_channel,handle_cast,2,
>                   [{file,"src/rabbit_channel.erl"},{line,470}]},
>               {gen_server2,handle_msg,2,
>                   [{file,"src/gen_server2.erl"},{line,1047}]},
>               {proc_lib,init_p_do_apply,3,
>                   [{file,"proc_lib.erl"},{line,239}]}]}}},
>  [{rabbit_channel_interceptor,call_module,4,
>       [{file,"src/rabbit_channel_interceptor.erl"},{line,74}]},
>   {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
>   {rabbit_channel,handle_cast,2,[{file,"src/rabbit_channel.erl"},{line,470}]},
>   {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1047}]},
>   {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
> 
> =WARNING REPORT==== 11-Jan-2018::11:51:14 ===
> Non-AMQP exit reason '{{case_clause,
>                         {'EXIT',
>                          {undef,
>                           [{os,system_time,[seconds],[]},
>                            {rabbit_timestamp_interceptor,intercept,3,
>                             [{file,"src/rabbit_timestamp_interceptor.erl"},
>                              {line,46}]},
>                            {rabbit_channel_interceptor,call_module,4,
>                             [{file,"src/rabbit_channel_interceptor.erl"},
>                              {line,74}]},
>                            {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
>                            {rabbit_channel,handle_cast,2,
>                             [{file,"src/rabbit_channel.erl"},{line,470}]},
>                            {gen_server2,handle_msg,2,
>                             [{file,"src/gen_server2.erl"},{line,1047}]},
>                            {proc_lib,init_p_do_apply,3,
>                             [{file,"proc_lib.erl"},{line,239}]}]}}},
>                        [{rabbit_channel_interceptor,call_module,4,
>                          [{file,"src/rabbit_channel_interceptor.erl"},
>                           {line,74}]},
>                         {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
>                         {rabbit_channel,handle_cast,2,
>                          [{file,"src/rabbit_channel.erl"},{line,470}]},
>                         {gen_server2,handle_msg,2,
>                          [{file,"src/gen_server2.erl"},{line,1047}]},
>                         {proc_lib,init_p_do_apply,3,
>                          [{file,"proc_lib.erl"},{line,239}]}]}'
> 
> =INFO REPORT==== 11-Jan-2018::11:51:14 ===
> closing AMQP connection <0.440.0> (_IP_:55842 -> _IP_:5672, vhost: '/', user: 'admin')

My activated plugins are as follows ($ rabbitmq-plugins list):

> Configured: E = explicitly enabled; e = implicitly enabled
>  | Status:   * = running on rabbit@st0cvm3000839
>  |/
> [e*] amqp_client                       3.6.14
> [e*] cowboy                            1.0.4
> [e*] cowlib                            1.0.2
> [  ] rabbitmq_amqp1_0                  3.6.14
> [  ] rabbitmq_auth_backend_ldap        3.6.14
> [  ] rabbitmq_auth_mechanism_ssl       3.6.14
> [  ] rabbitmq_consistent_hash_exchange 3.6.14
> [  ] rabbitmq_event_exchange           3.6.14
> [  ] rabbitmq_federation               3.6.14
> [  ] rabbitmq_federation_management    3.6.14
> [  ] rabbitmq_jms_topic_exchange       3.6.14
> [E*] rabbitmq_management               3.6.14
> [e*] rabbitmq_management_agent         3.6.14
> [  ] rabbitmq_management_visualiser    3.6.14
> [E*] rabbitmq_message_timestamp        _[Note: no Version Number]_
> [  ] rabbitmq_mqtt                     3.6.14
> [  ] rabbitmq_random_exchange          3.6.14
> [  ] rabbitmq_recent_history_exchange  3.6.14
> [  ] rabbitmq_sharding                 3.6.14
> [  ] rabbitmq_shovel                   3.6.14
> [  ] rabbitmq_shovel_management        3.6.14
> [  ] rabbitmq_stomp                    3.6.14
> [  ] rabbitmq_top                      3.6.14
> [  ] rabbitmq_tracing                  3.6.14
> [  ] rabbitmq_trust_store              3.6.14
> [e*] rabbitmq_web_dispatch             3.6.14
> [  ] rabbitmq_web_mqtt                 3.6.14
> [  ] rabbitmq_web_mqtt_examples        3.6.14
> [  ] rabbitmq_web_stomp                3.6.14
> [  ] rabbitmq_web_stomp_examples       3.6.14
> [  ] sockjs                            0.3.4

I don't understand: what is the issue?

**Comment by michaelklishin** [comment]
The message means that a standard library function this plugin uses is not available.

You need to use at least Erlang 18 with this plugin. Since 18 has known issues that can cause the node to not shut down or not accept new connections, you should use 19.3.6 or 20.x.

Or better yet, move to 3.7.x which requires Erlang 19.3 and has a version of this plugin as well as other community ones produced against each new patch release of RabbitMQ.

**Comment by maess89** [comment]
Thanks, it solved my issue!

**Comment by michaelklishin** [comment]
We try to specify what Erlang version a plugin requires (if it’s different from core RabbitMQ). Apparently that’s not the case for this plugin, I’ll fix this when I’m near a physical keyboard.
