### ISSUE TITLE
Timestamp as message exits broker

### ISSUE THREAD

**Issue by akoutmos** [rabbitmq/rabbitmq-message-timestamp#25]
Not sure if this is a piece of functionality that belongs in this plugin or a separate one (or if this is even a bad idea). At a high level I was wondering if it would be possible to also attach the timestamp when the message was consumed from the queue.

For some background, the reason that this would be useful is that as part of a metrics/monitoring solution, it would be good to keep an eye on how long messages are waiting in queue to be processed. This can help help drive consumer scale up/down solutions. Without keeping track of timings at the message queue layer, you risk having inaccurate measurements between producers/consumers due to clock drift if the consumers/producers are on different servers.

**Comment by michaelklishin** [comment]
There is only one timestamp field per message. A similar plugin could try to hook into `basic.deliver` frames but there isn't much demand for this feature. Also, I'm not sure how this should work in case of redeliveries.

Clock drift is equally applicable to RabbitMQ nodes as queue master location isn't guaranteed to be [on] the same node where the consumer is.

**Comment by michaelklishin** [comment]
Message rates and the number of messages in Ready state (and its dynamic over time) can and commonly are used for this purpose. It don't see any obvious benefits to tracking how a long a message has been enqueued. How this time window should be computed in the presence of [long running consumers and automatic redeliveries](https://www.rabbitmq.com/confirms.html#automatic-requeueing) is also not clear, unlike with the backlog and delivery rate metrics.

**Comment by akoutmos** [comment]
Thanks for the feedback! I'll ponder on the points that you brought up. Much appreciated :)
