### ISSUE TITLE
Plugin doesn't support current server version. Actual broker version: "3.8.0"

### ISSUE THREAD

**Issue by yderi** [rabbitmq/rabbitmq-message-timestamp#27]
Hello, 
After upgrading Rabbit server to ver 3.8.0 - plugin "rabbitmq_message_timestamp" stop working 

```
sudo rabbitmq-plugins enable rabbitmq_message_timestamp
Enabling plugins on node rabbit@lb-serv:
rabbitmq_message_timestamp
Error:
Failed to enable some plugins:
    rabbitmq_message_timestamp:
        Plugin doesn't support current server version. Actual broker version: "3.8.0", supported by the plugin: ["3.7.0-3.7.x"]
```

**Comment by michaelklishin** [comment]
It does as of https://github.com/rabbitmq/rabbitmq-message-timestamp/commit/938164cb053e321d5b3d148b6ccb1ff094c99c5d. See [Releases](https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/tag/v3.8.0).
