### ISSUE TITLE
Unable to build after rabbitmq-server moved to erlang.mk

### ISSUE THREAD

**Issue by abecadel** [rabbitmq/rabbitmq-message-timestamp#3]
Missing umbrella.mk file - caused by changing build system.

**Comment by videlalvaro** [comment]
Yes, we still need to migrate our custom plugins to the new build system

**Comment by abecadel** [comment]
Hi
Forgive me asking, but could U guys tell me what priority is this issue?

**Comment by michaelklishin** [comment]
It will be fixed by the time 3.6.0 ships.

**Comment by dumbbell** [comment]
This plugin was migrated to erlang.mk.

**Comment by abecadel** [comment]
Thanks!
