### ISSUE TITLE
support 3.9

### ISSUE THREAD

**Issue by kudrmudr** [rabbitmq/rabbitmq-message-timestamp#33]
there is no asset which support 3.9 https://github.com/rabbitmq/rabbitmq-message-timestamp/releases

**Comment by yderi** [comment]
Hello everyone

Cannot build myself, make fail:
`make[2]: *** [../../erlang.mk:5453: ebin/rabbit_common.app] Error 1
make[1]: *** [../../erlang.mk:5195: app] Error 2
make[1]: Leaving directory '/home/dev/tmp/rabbitmq-message-timestamp/.erlang.mk/rabbitmq-server/deps/rabbit_common'
make: *** [erlang.mk:4512: deps] Error 2
`

Can anyone point for .ez file for Rabbitmq 3.9.0 version support?

**Comment by lukebakken** [comment]
This is related to https://github.com/gotthardp/rabbitmq-email/issues/45

Once I'm done with the above, I can start working on this plugin.

**Comment by mronnblom-cint** [comment]
Seeing as there is now a release 3.9.11 available, shouldn't this issue be closed?

**Comment by lukebakken** [comment]
Resolved by https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/tag/v3.9.11
