### ISSUE TITLE
Support 3.11.x

### ISSUE THREAD

**Issue by frazjp65** [rabbitmq/rabbitmq-message-timestamp#34]
[Version 3.11.0 of rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.11.0) has been released. Please make a new release of this plugin so it will work with the new version.

**Comment by lukebakken** [comment]
I will get this next week.

**Comment by michaelklishin** [comment]
[Done](https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/tag/v3.11.1)

**Comment by lukebakken** [comment]
Thanks @michaelklishin
