### ISSUE TITLE
support 3.12.x

### ISSUE THREAD

**Issue by Guzzi** [rabbitmq/rabbitmq-message-timestamp#39]
rabbit server 3.12.0 has beed released - could you please update this plugin so it will be supported by 3.12.x server releases?
@lukebakken ?

**Comment by michaelklishin** [comment]
That should no longer be necessary as of https://github.com/rabbitmq/rabbitmq-server/pull/8188.
The interceptor provided by this plugin is now in the core:

``` ini
# if you want the plugin to overwrite the application-provided timestamp
message_interceptors.incoming.set_header_timestamp.overwrite = true

## OR

# if you DO NOT want the plugin to overwrite the application-provided timestamp
message_interceptors.incoming.set_header_timestamp.overwrite = false
```

**Comment by michaelklishin** [comment]
The README [says more or less the same thing](https://github.com/rabbitmq/rabbitmq-message-timestamp#supported-rabbitmq-versions).

**Comment by Guzzi** [comment]
@michaelklishin tbh I missed that information - thanks a lot for pointing me to that!
