### ISSUE TITLE
Build without using umbrella project

### ISSUE THREAD

**Issue by biiiipy** [rabbitmq/rabbitmq-message-timestamp#4]
Is it possible to build this with the new build process for RabbitMQ 3.6 without using umbrella project?

**Comment by michaelklishin** [comment]
```
git clone git@github.com:rabbitmq/rabbitmq-message-timestamp.git
# [snip]
cd rabbitmq-message-timestamp
make
# [snip]
make dist
# [snip]
ls plugins/*
```

**Comment by biiiipy** [comment]
This works. *README.md* probably should promote this build system instead of umbrella (which I couldn't get to build for some reason :confused: ).
Thank you (again :smile: )!

**Comment by michaelklishin** [comment]
Done.
